# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1000, 720)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.tabs = QtWidgets.QTabWidget(self.centralwidget)
        self.tabs.setObjectName("tabs")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.tab)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.plot_1 = QtWebEngineWidgets.QWebEngineView(self.tab)
        self.plot_1.setObjectName("plot_1")
        self.gridLayout_2.addWidget(self.plot_1, 0, 0, 1, 1)
        self.tabs.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.tab_2)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.plot_2 = QtWebEngineWidgets.QWebEngineView(self.tab_2)
        self.plot_2.setObjectName("plot_2")
        self.gridLayout_3.addWidget(self.plot_2, 0, 0, 1, 1)
        self.tabs.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.tab_3)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(self.tab_3)
        self.frame.setMaximumSize(QtCore.QSize(16777215, 50))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.cases = QtWidgets.QPushButton(self.frame)
        self.cases.setObjectName("cases")
        self.horizontalLayout.addWidget(self.cases)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.deaths = QtWidgets.QPushButton(self.frame)
        self.deaths.setObjectName("deaths")
        self.horizontalLayout.addWidget(self.deaths)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.gridLayout_4.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.frame)
        self.plot_3 = QtWebEngineWidgets.QWebEngineView(self.tab_3)
        self.plot_3.setObjectName("plot_3")
        self.verticalLayout.addWidget(self.plot_3)
        self.gridLayout_6.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.tabs.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.tab_4)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.plot_4 = QtWebEngineWidgets.QWebEngineView(self.tab_4)
        self.plot_4.setObjectName("plot_4")
        self.gridLayout_5.addWidget(self.plot_4, 0, 0, 1, 1)
        self.tabs.addTab(self.tab_4, "")
        self.gridLayout.addWidget(self.tabs, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1000, 21))
        self.menubar.setObjectName("menubar")
        self.menufile = QtWidgets.QMenu(self.menubar)
        self.menufile.setObjectName("menufile")
        self.menuexport = QtWidgets.QMenu(self.menufile)
        self.menuexport.setObjectName("menuexport")
        self.menuBar_Chart = QtWidgets.QMenu(self.menuexport)
        self.menuBar_Chart.setObjectName("menuBar_Chart")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionMap = QtWidgets.QAction(MainWindow)
        self.actionMap.setObjectName("actionMap")
        self.actionScatter = QtWidgets.QAction(MainWindow)
        self.actionScatter.setObjectName("actionScatter")
        self.actionCases = QtWidgets.QAction(MainWindow)
        self.actionCases.setObjectName("actionCases")
        self.actionDeaths = QtWidgets.QAction(MainWindow)
        self.actionDeaths.setObjectName("actionDeaths")
        self.menuBar_Chart.addAction(self.actionCases)
        self.menuBar_Chart.addAction(self.actionDeaths)
        self.menuexport.addAction(self.actionMap)
        self.menuexport.addAction(self.actionScatter)
        self.menuexport.addAction(self.menuBar_Chart.menuAction())
        self.menufile.addAction(self.menuexport.menuAction())
        self.menubar.addAction(self.menufile.menuAction())

        self.retranslateUi(MainWindow)
        self.tabs.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.tabs.setTabText(self.tabs.indexOf(self.tab), _translate("MainWindow", "Map"))
        self.tabs.setTabText(self.tabs.indexOf(self.tab_2), _translate("MainWindow", "Bubble"))
        self.cases.setText(_translate("MainWindow", "Cases"))
        self.deaths.setText(_translate("MainWindow", "Deaths"))
        self.tabs.setTabText(self.tabs.indexOf(self.tab_3), _translate("MainWindow", "Bar Charts"))
        self.tabs.setTabText(self.tabs.indexOf(self.tab_4), _translate("MainWindow", "Bubble Increase"))
        self.menufile.setTitle(_translate("MainWindow", "File"))
        self.menuexport.setTitle(_translate("MainWindow", "Video Export"))
        self.menuBar_Chart.setTitle(_translate("MainWindow", "Bar Chart"))
        self.actionMap.setText(_translate("MainWindow", "Map"))
        self.actionScatter.setText(_translate("MainWindow", "Bubble"))
        self.actionCases.setText(_translate("MainWindow", "Cases"))
        self.actionDeaths.setText(_translate("MainWindow", "Deaths"))
from PyQt5.QtWebEngineWidgets import *


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
